development:
  adapter: postgresql
  encoding: unicode
  database: foojee_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: foojee_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: foojee_production
  pool: 5
